FORMAT: 1A
HOST: https://swapi-lite.herokuapp.com/api/v1

# SWAPI-LITE
A Movie API for listing the names of Star Wars movies along with their opening crawls and comment counts, adding and listing anonymous comments for a movie, and getting the character list for a movie.
See *INSTALL.md* on how to use locally

API ROOT: https://swapi-lite.herokuapp.com/api/v1

### Summary
**Total Endpoints -** 4


## Movies [/movies]

This endpoint returns a list of star wars movies with their comment count, opening crawls and chracter list

### Retrive all movies [GET]

+ Response 200 (application/json)

        {
            "success": true,
            message: "operation successful",
            data:{
                statusCode: 200,
                results: 6,
                description: "list of star wars movies",
                movies: [
                    {
                        "title": "",
                        "opening_crawl":"",
                        "characters":[],
                        "comments": 4
                    }
                ]
            }
        }
        

## Comments [/comments{?movie}]

The comments endpoint is used to add and retrieve comments on a movie

### Retrieve All Comments [GET]

+ Parameters
    + movie(optional) - name of movie to retrieve comments 


+ Response 200 (application/json)
te
    + Body
        
            {
                "success": true,
                "message": "operation successful",
                "data": {
                    "statusCode": 200
                    "description": "successfully retrived all comments",
                    "comments": [
                        {
                            "id": 3,
                            "comment": "hello star wars lovers",
                            "ip_address": "192.168.0.3",
                            "movie": "A New Hope",
                            "createdAt": "2020-09-11T17:46:19.000Z"
                        }
                    ]
                }
            }

### Add New Comment [POST]

+ Request (application/json)

        {
            "comment": "I love this movie",
            "movie_title":"A New Hope"
        }

+ Response 201 (application/json)

    + Body

            {
                "success": true,
                "message": "operation successful",
                "data": {
                    "statusCode": 201,
                    "description": "comment added successfully",
                    "comment": {
                        "comment": "I love this movie",
                        "movies_title":"A New Hope"
                    }
                }
            }
            
            
## Characters [/characters{?movie}]

Ednpoint to retrieve all characters in a movie

### Get All Characters in a Movie [GET]

+ Parameters
    + movie(required) - name of movie to retrive characters from

+ Response 200 (application/json)

    + body
    
            {
                "success": true,
                "message": "operation successful",
                "data": {
                    "statusCode": 200,
                    "description": "successfully retrieved movie characters",
                    "movie": "A New Hope"
                    "characters": []
                }
            }